### ISSUE TITLE
Add installation via CocoaPods (and carthage)

### ISSUE THREAD

**Issue by driver733** [dehlen/OMDBAPI#1]

**Comment by dehlen** [comment]
I'll add support in the next couple of days. Thanks for your feedback.

**Comment by dehlen** [comment]
I added a podspec file in order to install via cocoapods. I will upload the podspec file to the Spec repository so it will be available on the cocoapods.org website. 

Carthage support will follow very soon. I am currently very busy but when I find some time I'll try to set it up.

Cheers,
David

**Comment by dehlen** [comment]
Ok podspec is submitted. Should be working fine now to install via Cocoapods.
